CREATE TABLE users (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, email VARCHAR(128) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(128) DEFAULT 'student');
CREATE TABLE profiles (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, users_id INT NOT NULL UNIQUE, firstname VARCHAR(128) NOT NULL, lastname VARCHAR(128) NOT NULL, bio VARCHAR(1024), github VARCHAR(255), linkedin VARCHAR(255), level INT, FOREIGN KEY (users_id) REFERENCES users(id));
CREATE TABLE questions (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, question VARCHAR(255) NOT NULL, answers VARCHAR(1024) NOT NULL);
CREATE TABLE exams (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, description VARCHAR(128) NOT NULL, questions VARCHAR(1024) NOT NULL);
CREATE TABLE assesments (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, assesment VARCHAR(1024) NOT NULL);


CREATE TABLE assesment_results (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
assesment_id INT NOT NULL, 
user_id INT NOT NULL,
results VARCHAR(1024) NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (assesment_id) REFERENCES assesments(id)
);